# PayFleet Application Configuration
# This file configures our entire Spring Boot application

# Server Configuration
server:
  port: 8080  # Standard HTTP port
  servlet:
    context-path: /payfleet  # Base path: http://localhost:8080/payfleet

# Application Information
spring:
  application:
    name: payfleet-payments-system

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/payfleet
    username: payfleet_user
    password: payfleet_pass
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update  # Automatically creates/updates database tables
    show-sql: true     # Shows SQL queries in console (for learning)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # Pretty-print SQL queries

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092

    # Producer Configuration
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
      retries: 3
      acks: all

    # Consumer Configuration
    consumer:
      group-id: payfleet-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.payfleet.dto"

    # Topic Configuration
    template:
      default-topic: payment-events

# PayFleet Kafka Topics
payfleet:
  kafka:
    topics:
      payment-events: payment-events
      payment-notifications: payment-notifications
      account-updates: account-updates

# Logging Configuration - helps us debug issues
logging:
  level:
    com.payfleet: DEBUG    # Detailed logs for our code
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Management Endpoints - health checks, metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always